spring.application.name=recommendation-service

environment.url=http://localhost:8084

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite

spring.ai.google.genai.chat.options.temperature=0.0
spring.ai.google.genai.chat.options.max-output-tokens=1024

spring.config.import=optional:file:recommendation/.env[.properties]

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/,http://localhost:8762/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
