spring.application.name=recommendation

environment.url=http://localhost:8080

server.port=8081

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite

spring.ai.google.genai.chat.options.temperature=0.0
spring.ai.google.genai.chat.options.max-output-tokens=1024

spring.config.import=optional:file:recommendation/.env[.properties]
