### llm호출 답변 생성
GET http://localhost:8763/api/recommendation/llm?message=지금 강의실 이산화탄소 농도가 1100ppm인데 어떡할까?

### llm호출
POST http://localhost:8763/api/recommendation/chat
Content-Type: application/json

{
  "userId": "3412",
  "lastMentionRoomId": 10,
  "message": "1번팀이 관리중인 1번 강의실 정보좀",
  "requestedAt": "2026-07-21T11:20:00"
}